name: "CI: NixOS Flake Test"

on:
  pull_request:
  push:
    branches:
      - master 

jobs:
  test-flake:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ— Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: âœ… Run Flake Check
        run: nix flake check --show-trace

      - name: ğŸ”¨ Build NixOS System Configuration (Nixstation)
        run: nix build .#nixosConfigurations.Nixstation.config.system.build.toplevel

      - name: ğŸ–¥ Run NixOS VM Test (Optional)
        run: nix build .#nixosConfigurations.Nixstation.config.system.build.vm && ./result/bin/run-nixos-vm

      - name: ğŸ§¹ Cleanup
        if: always()
        run: nix-collect-garbage -d
